version: '2'
services:
  payments_service_v2:
      build: .
      container_name: payments_service_v2
      networks:
          - servers_external_network
      ports:
          - 82:80
      env_file:
          - ./.env
      tty: true
      volumes:
          - .:/src
          - .:/usr/src/app
          - ./bin/log/payments_service_v2:/var/log/application/payments_service_v2
networks:
  servers_external_network:
    external: true
