apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-service-v2-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: payments-service-v2
      port:
        number: 80
  rules:
    - host: staging-ps-v2.kongapay.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: payments-service-v2
                port:
                  number: 80
