apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk-payments-service-ingress
  namespace: skaleet
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: kongapay-tls
  defaultBackend:
    service:
      name: sk-payments-service
      port:
        number: 80
  rules:
    - host: sk-ps.kongapay.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: sk-payments-service
                port:
                  number: 80
